remote_theme: broccolini/swiss
theme_color: black

title: MI-AI Assistant
description: An experimental AI chatbot using Motivational Interviewing techniques
show_downloads: true

# Navigation
header_pages:
  - index.md
  - methodology.md

# Social/Repository links
github_repo: "https://github.com/[your-username]/mi-ai" 